version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install bandit flask
  build:
    commands:
      - echo "Starting Manual & Automated Security Audit..."
      # 1. Automated Scan
      - bandit -r . -lll || true
      # 2. Manual "Kill Switch" - If 'ADMIN_PASSWORD' is found WITHOUT a '#', fail the build.
      - if grep -q "ADMIN_PASSWORD =" secure_app/app.py; then echo "VULNERABILITY FOUND! Terminating Build..."; exit 1; fi
      - echo "No hardcoded credentials found. Proceeding..."
artifacts:
  files:
    - "**/*"