version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install bandit
  build:
    commands:
      - bandit -r . -lll -f html -o bandit-report.html
artifacts:
  files:
    - bandit-report.html