version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing security tools..."
      - pip install bandit
      
  build:
    commands:
      - echo "Starting Bandit SAST scan..."
      # Running Bandit. We only check for HIGH severity issues (-lll).
      # IMPORTANT: Do NOT put '|| true' at the end of this line!
      - bandit -r . -lll -f txt -o bandit-report.txt
      
      # If Bandit finds an error, AWS CodeBuild will instantly kill the pipeline right here.
      # The code below will ONLY run if Bandit says the code is 100% safe.
      - echo "Bandit scan passed! Proceeding to build..."
      
  post_build:
    commands:
      - echo "Uploading security reports to S3..."
      - aws s3 cp bandit-report.txt s3://devops-security-reports-abhiii265/
      - echo "Packaging complete. Ready for CodeDeploy."

artifacts:
  files:
    - '**/*'